### ISSUE TITLE
Failed to activate the emmet-jsx-props package

### ISSUE THREAD

**Issue by rr250** [iJigg/emmet-jsx-props#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [emmet-jsx-props](https://github.com/iJigg/emmet-jsx-props) package 1.2.5

### Stack Trace

Failed to activate the emmet-jsx-props package

```
At Path must be a string. Received null

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at Object.activate (/packages/emmet-jsx-props/lib/emmet-jsx-props.js:6:28)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.1/resources/app/src/package.js:255:25)
    at ~/AppData/Local/atom/app-1.23.1/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.23.1/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.23.1/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.23.1/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.23.1/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.23.1/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.23.1/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.23.1/resources/app/src/package-manager.js:647:50)
    at ~/AppData/Local/atom/app-1.23.1/resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
css-snippets 1.1.0 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
emmet-jsx-props 1.2.5 
emmet-snippets-compatibility 1.0.6 
html-to-css 0.2.2 
jackhammer-syntax 1.1.0 
```

**Comment by iJigg** [comment]
Can you supply steps to reproduce? 
Running same setup and not able to reproduce.
